definitions:
  app.DiscussionSourceInfo:
    properties:
      created_at:
        type: string
      id:
        type: integer
      source_closed:
        type: boolean
      source_id:
        type: string
      source_type:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  app.OptionalTopic:
    properties:
      discussion:
        items:
          items:
            $ref: '#/definitions/app.DiscussionSourceInfo'
          type: array
        type: array
      summary:
        type: string
    type: object
  app.TopicsToReviewDTO:
    properties:
      cadidates:
        additionalProperties:
          items:
            $ref: '#/definitions/domain.TopicToReview'
          type: array
        type: object
      selected:
        items:
          $ref: '#/definitions/domain.TopicToReview'
        type: array
    type: object
  controller.ResponseData:
    properties:
      code:
        type: string
      data: {}
      msg:
        type: string
    type: object
  controller.reqToAddSolution:
    properties:
      data:
        items:
          $ref: '#/definitions/app.OptionalTopic'
        type: array
    type: object
  controller.reqToReview:
    properties:
      data:
        items:
          $ref: '#/definitions/app.OptionalTopic'
        type: array
    type: object
  controller.reqToUpdateSelected:
    properties:
      selected:
        items:
          $ref: '#/definitions/domain.TopicToReview'
        type: array
    type: object
  domain.DiscussionSourceToReview:
    properties:
      created_at:
        type: string
      id:
        type: integer
      imported_at:
        type: string
      source_closed:
        type: boolean
      source_id:
        type: string
      source_type:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
  domain.TopicToReview:
    properties:
      category:
        type: string
      dss:
        items:
          $ref: '#/definitions/domain.DiscussionSourceToReview'
        type: array
      order:
        type: integer
      resolved:
        type: boolean
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/hot-topic/{community}/solution:
    post:
      consumes:
      - application/json
      description: add topic solution
      parameters:
      - description: lowercase community name, like openubmc, cann
        in: path
        name: community
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToAddSolution'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Internal: []
      summary: ToReview
      tags:
      - HotTopic
  /v1/hot-topic/{community}/to-review:
    post:
      consumes:
      - application/json
      description: upload topics to review
      parameters:
      - description: lowercase community name, like openubmc, cann
        in: path
        name: community
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToReview'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Internal: []
      summary: Create
      tags:
      - TopicReview
  /v1/topic-review/{community}:
    get:
      consumes:
      - application/json
      description: get topic review info
      parameters:
      - description: lowercase community name, like openubmc, cann
        in: path
        name: community
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.TopicsToReviewDTO'
      security:
      - Internal: []
      summary: Get
      tags:
      - TopicReview
    put:
      consumes:
      - application/json
      description: update the selected topics
      parameters:
      - description: lowercase community name, like openubmc, cann
        in: path
        name: community
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.reqToUpdateSelected'
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/controller.ResponseData'
      security:
      - Internal: []
      summary: Update
      tags:
      - TopicReview
securityDefinitions:
  Internal:
    description: Type "Internal" followed by a space and internal token.
    in: header
    name: TOKEN
    type: apiKey
swagger: "2.0"
